# The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database.

version: "3.8"

services:
    postgres:
      image: postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=goods
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: postgres
    django:
        build: .
        container_name: django
        command: >
          bash -c "python manage.py migrate
          && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports:
            - 8000:8000
        depends_on:
            - postgres
        restart:
          always
