# Generated by Django 3.2.6 on 2022-07-10 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_good_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
