# Generated by Django 3.2.6 on 2022-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='generalType',
            field=models.CharField(default='shirt', max_length=100),
        ),
    ]
