# Generated by Django 3.2.6 on 2022-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_good_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='stock_1',
            field=models.CharField(default='xs_100 s_100 m_100 l_100 xl_100', max_length=100),
        ),
    ]
