# Generated by Django 3.2.6 on 2022-07-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_good_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='stock_1',
            new_name='stock',
        ),
    ]
