# Generated by Django 3.2.6 on 2022-07-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_stock_1_good_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
