# Generated by Django 3.2.6 on 2022-07-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
